"""Core infrastructure package for the AI Resume Analyzer."""

from core.config import Settings, get_settings
from core.exceptions import (
    ResumeAnalyzerError,
    FileProcessingError,
    UnsupportedFileTypeError,
    FileTooLargeError,
    FileCorruptedError,
    TextExtractionError,
    AnalysisError,
    AIServiceError,
    OpenAITimeoutError,
    OpenAIRateLimitError,
    OpenAITokenLimitError,
    OpenAISchemaError,
    ScoringError,
    SummaryGenerationError,
    RecommendationError,
    JobDatabaseError,
    MatchingError,
    ReportError,
    PDFGenerationError,
    ReportNotFoundError,
    DatabaseError,
    ConnectionError as DBConnectionError,
    MigrationError,
    IntegrityError,
    ConfigurationError,
    MissingAPIKeyError,
    InvalidConfigError,
)

__all__ = [
    "Settings",
    "get_settings",
    "ResumeAnalyzerError",
    "FileProcessingError",
    "UnsupportedFileTypeError",
    "FileTooLargeError",
    "FileCorruptedError",
    "TextExtractionError",
    "AnalysisError",
    "AIServiceError",
    "OpenAITimeoutError",
    "OpenAIRateLimitError",
    "OpenAITokenLimitError",
    "OpenAISchemaError",
    "ScoringError",
    "SummaryGenerationError",
    "RecommendationError",
    "JobDatabaseError",
    "MatchingError",
    "ReportError",
    "PDFGenerationError",
    "ReportNotFoundError",
    "DatabaseError",
    "DBConnectionError",
    "MigrationError",
    "IntegrityError",
    "ConfigurationError",
    "MissingAPIKeyError",
    "InvalidConfigError",
]