"""
Report domain models.

Defines data structures for downloadable analysis reports
including PDF and JSON formats.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field


class ReportFormat(str, Enum):
    """Supported report output formats."""

    PDF = "pdf"
    JSON = "json"


class ReportSection(BaseModel):
    """A single section within a report."""

    title: str = Field(description="Section title")
    content: str = Field(description="Section content (HTML for PDF, text for JSON)")
    order: int = Field(default=0, description="Display order in the report")
    icon: Optional[str] = Field(default=None, description="Optional section icon")


class ReportMetadata(BaseModel):
    """Metadata for a generated report."""

    report_id: str = Field(description="Unique report identifier")
    analysis_id: int = Field(description="ID of the source analysis")
    created_at: datetime = Field(default_factory=datetime.now, description="Report generation time")
    format: ReportFormat = Field(default=ReportFormat.PDF, description="Report format")
    file_size_bytes: Optional[int] = Field(default=None, description="Report file size")
    file_path: Optional[str] = Field(default=None, description="Path to the generated file")
    version: str = Field(default="1.0.0", description="Report template version")


class AnalysisReport(BaseModel):
    """A complete analysis report ready for export."""

    metadata: ReportMetadata = Field(
        default_factory=lambda: ReportMetadata(
            report_id="",
            analysis_id=0,
        ),
        description="Report metadata",
    )
    sections: list[ReportSection] = Field(
        default_factory=list,
        description="Report sections in order",
    )
    candidate_name: str = Field(default="", description="Candidate name")
    overall_score: float = Field(default=0.0, description="Overall resume score")
    summary: str = Field(default="", description="Executive summary")

    def add_section(self, title: str, content: str, icon: Optional[str] = None) -> None:
        """Add a section to the report.

        Args:
            title: Section title.
            content: Section content.
            icon: Optional icon identifier.
        """
        self.sections.append(
            ReportSection(
                title=title,
                content=content,
                order=len(self.sections),
                icon=icon,
            )
        )

    def to_html(self) -> str:
        """Convert the report to HTML for PDF generation.

        Returns:
            str: HTML string representation of the report.
        """
        sections_html = "\n".join(
            f"""
            <div class="report-section">
                <h2>{s.title}</h2>
                <div class="section-content">{s.content}</div>
            </div>
            """
            for s in sorted(self.sections, key=lambda x: x.order)
        )

        return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>Resume Analysis Report</title>
            <style>
                body {{ font-family: 'Helvetica', 'Arial', sans-serif; margin: 40px; color: #333; }}
                h1 {{ color: #1a73e8; border-bottom: 2px solid #1a73e8; padding-bottom: 10px; }}
                h2 {{ color: #2c3e50; margin-top: 30px; }}
                .report-section {{ margin-bottom: 25px; }}
                .section-content {{ line-height: 1.6; }}
                .score {{ font-size: 48px; font-weight: bold; color: #1a73e8; text-align: center; }}
                .footer {{ margin-top: 50px; font-size: 12px; color: #999; text-align: center; }}
            </style>
        </head>
        <body>
            <h1>Resume Analysis Report</h1>
            <p><strong>Candidate:</strong> {self.candidate_name}</p>
            <div class="score">{self.overall_score:.0f}/100</div>
            <p style="text-align:center;">Overall Resume Score</p>
            {sections_html}
            <div class="footer">
                <p>Generated by AI Resume Analyzer on {self.metadata.created_at.strftime('%B %d, %Y')}</p>
            </div>
        </body>
        </html>
        """